export const itemCatalog = [
  {
    id: 1,
    title: "Пластиковые стаканы",

    description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. ",
    shopOfBrand: "Selling Thing",
    brand: "Nice",
    color: ["#88cadd"],
    categorate: "Посуда",
    reviews: 5,
    availability: "in store",
    price: 10,
    count: 1,
    imgSrc: ["../images/stul.webp"],
  },

  {
    id: 2,
    title: "Брэндовые часы",
    description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
    shopOfBrand: "Selling Thing",
    brand: "Nice",
    color: ["#88cadd"],
    categorate: "Посуда",
    reviews: 5,
    availability: "in store",
    price: 10,
    count: 1,
    imgSrc: ["../images/Orange and Gray Tag Cart Virtual Shop Logo.png"],
  },
  {
    id: 3,
    title: "Фирменые очки",
    description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
    shopOfBrand: "Selling Thing",
    brand: "Nice",
    color: ["#88cadd"],
    categorate: "Посуда",
    reviews: 5,
    availability: "in store",
    price: 1000,
    count: 1,
    imgSrc: ["../images/podstavka.webp","../images/stul.webp"],
  },
  {
    id: 4,
    title: "kosot plastic",
    description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
    shopOfBrand: "Selling Thing",
    brand: "Nice",
    color: ["#88cadd"],
    categorate: "Одежда",
    reviews: 5,
    availability: "in store",
    price: 10,
    count: 1,
    imgSrc: [
      "https://images.unsplash.com/photo-1572635196237-14b3f281503f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=880&q=80",
    ],
  },
  {
    id: 5,
    title: "kosot plastic",
    description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
    shopOfBrand: "Selling Thing",
    brand: "Nice",
    color: ["#88cadd"],
    categorate: "Одежда",
    reviews: 5,
    availability: "in store",
    price: 10,
    count: 1,
    imgSrc: ["../images/julia-zolotova-KHhhpr8_GAs-unsplash.jpg"]
  },
  {
    id: 6,
    title: "kosot plastic",
    description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
    shopOfBrand: "Selling Thing",
    brand: "Nice",
    color: ["#88cadd"],
    categorate: "Одежда",
    reviews: 5,
    availability: "in store",
    price: 100,
    count: 1,
    imgSrc: ["../images/kobu-agency-TWIRIAizZFU-unsplash.jpg"],
  },
  {
    id: 7,
    title: "kosot plastic",
    description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
    shopOfBrand: "Selling Thing",
    brand: "Nice",
    color: ["#88cadd"],
    categorate: "Мебель",
    reviews: 5,
    availability: "in store",
    price: 50,
    count: 1,
    imgSrc: ["../images/vladimir-gladkov-Y7i_LU1L-Jo-unsplash.jpg"],
  },
  {
    id: 8,
    title: "kosot plastic",
    description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
    shopOfBrand: "Selling Thing",
    brand: "Nice",
    color: ["#88cadd"],
    categorate: "Мебель",
    reviews: 5,
    availability: "in store",
    price: 10,
    count: 1,
    imgSrc: ["../images/angelo-abear-IO8XRikqJU4-unsplash.jpg"],
  },
  {
    id: 9,
    title: "kosot plastic",
    description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
    shopOfBrand: "Selling Thing",
    brand: "Nice",
    color: ["#88cadd"],
    categorate: "Мебель",
    reviews: 5,
    availability: "in store",
    price: 80,
    count: 1,
    imgSrc: ["../images/stockvault-clown105702.jpg"],
  },
  {
    id: 10,
    title: "kosot plastic",
    description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
    shopOfBrand: "Selling Thing",
    brand: "Nice",
    color: ["#88cadd"],
    categorate: "Мебель",
    reviews: 5,
    availability: "in store",
    price: 10,
    count: 1,
    imgSrc:
      ["../images/stockvault-woman-posing-on-haystack-hazy-vintage-looks-with-copyspace221909.jpg"],
  },
  {
    id: 11,
    title: "kosot plastic",
    description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
    shopOfBrand: "Selling Thing",
    brand: "Nice",
    color: ["#88cadd"],
    categorate: "Электро-товары",
    reviews: 5,
    availability: "in store",
    price: 10,
    count: 1,
    imgSrc: ["../images/ракетки.webp"],
  },
];
